public class BillingDetailsController {
      //public Static String nextPage38{get;set;}
public BillingDetailsController(ApexPages.StandardController controller){
      
//nextPage38=generateOrderFormPDF.mapVFtest.get(generateOrderFormPDF.ProSSJ.get(generateOrderFormPDF.nextNumber).order__c).Scope_Of_Service_VFs__r.Name;
        //system.debug('nextNumber '+generateOrderFormPDF.nextNumber);
        //system.debug('nextPage38 '+nextPage38);
       
    }
}