public class CTX_ReceivableServiceWrapper {
    
    Public String   name;
    Public String   id;
    Public String   currencyType;
    Public String   cTBillingEntity;
    Public String   virtualAccountNumber;
    Public String   ownerName;
    Public String   pAN_TIN;
    Public String   sapBpCode;
    Public String   nameOfTheEntity;
    Public String   account;
    Public Decimal  activeARR;
    Public String   accountCSM;
    Public String   entityPAN;
    Public String   accountOwnerName;
    Public String   createdBy;
    Public String   lastModifiedBy;
    Public String   accountOwnerEmail;
    Public String   accountCSMEmail;
    Public String   sAPDB;
    Public String   accountOwnerId;
    Public String   accountCSMId;


}