public class QuoteConstants {

    public static  Boolean ISFIRSTTIMEQUOTE=TRUE;
    public static  Boolean ISFIRSTTIMEQLI=TRUE;
    public static  Boolean DISABLEQLIVAl=FALSE;
    //Quote Status picklist Values
    public static final String STATUS_DRAFT='Draft';
    public static final String STATUS_INQUOTEAPPROVALS='In Quote Approvals';
    public static final String STATUS_QUOTE_SENT='Quote Sent';
    public static final String STATUS_PRICE_NEGOTIATION='Price Negotiation';
    public static final String STATUS_QUOTE_ACCEPT='Quote Accept';
    public static final String STATUS_DOCUMENT_GENERATED='Document Generated';
    public static final string RENEWAL_QUOTE = 'Renewal Quote';
    
    //Quote Approval Status
    public static final String APPROVAL_NOT_REQUIRED='Not Required';
    public static final String APPROVAL_APPROVED='Approved';
    
    //Added by Raksha
      public static final String ESIGN_STATUS_ESIGN ='E-Sign';
    
    //Type of Integeration
    public static final String TYPE_OF_INTEGRATION_API_ONLY_BY_CT = 'API- Only by CT';	
    public static final String TYPE_OF_INTEGRATION_API_ONLY_BY_CUSTOMER = 'API- Only by Customer';
    public static final String TYPE_OF_INTEGRATION_FTP = 'FTP';
    public static final String TYPE_OF_INTEGRATION_EXCEL_CUSTOM_MAPPER = 'Excel/Custom Mapper';	
    public static final String TYPE_OF_INTEGRATION_TALLY_CONNECTOR = 'Tally Connector';
    public static final String TYPE_OF_INTEGRATION_SFTP_SI = 'SFTP-SI';
     public static final String TYPE_OF_INTEGRATION_AIRLINE = 'Airline';
        	
    
    
    
}