public class RecursiveTriggerHandler{
    public static Boolean isFirstTime 					= true;
    public static Boolean isFirstTimeRenewed 			= false;
    public static Boolean isFirstTimeOpportunity		= true;
    public static Integer isFirstTimeOpportunityCounter = 0;
    public static Boolean isFirstTimeGSTIN 				= TRUE;
    public static Boolean isAllowSAPBPCreation		 	= TRUE;
    public static Boolean runPassSAPBPCreationBatch		= TRUE;
    public static Boolean runCreateLogger				= TRUE;
}