public class SurveyResponseConstants {

    //Field ApiNames
    public static final String SUVERY_QUESTION_1='Survey_Question_1__c';
    
    public static final String SUVERY_QUESTION_2='Survey_Question_2__c';
    
    public static final String SUVERY_QUESTION_3='Survey_Question_3__c';
    
    //New addition for Survey question
    public static final String SUVERY_QUESTION_4='Survey_Question_4__c';
    
    public static final String SUVERY_RESPONSE_1='Survey_Response_1__c';
    
    public static final String SUVERY_RESPONSE_2='Survey_Response_2__c';
    
    public static final String SUVERY_RESPONSE_3='Survey_Response_3__c';
    
    //New addition for Survey question
    public static final String SUVERY_RESPONSE_4='Survey_Response_4__c';
    
    
    
}